version: '1.0.{build}'
image: Visual Studio 2019 
stack: node 18

clone_folder: ./src
shallow_clone: true

branches:
  only:
    -master

build: off
cache: off
build_script:
  - npm run build

test_script:
  - npm run lint && npm test