version: '1.0.{build}'
image: Visual Studio 2019
stack: node 18
branches:
  only:
    - master
shallow_clone: true

clone_folder: ./src
shallow_clone: true

build: off
cache: node_modules
build_script:
  - npm run build

test_script:
  - npm run lint && npm test
